name: Nox Tests

on:
  push

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Nox
        uses: excitedleigh/setup-nox@v2
      
      - name: Set up Python (Default to 3.12)
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 

      - name: Run Nox
        run: nox
        with:
          python-version: 3.12 
